# Generated by Django 5.0.6 on 2024-06-10 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0002_remove_carmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='car_app/media/'),
        ),
    ]
