# Generated by Django 5.0.6 on 2024-06-10 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0010_alter_brandmodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='des',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
