# Generated by Django 5.0.6 on 2024-06-10 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0012_commentmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cmt', to='car_app.carmodel'),
        ),
    ]
