# Generated by Django 5.0.6 on 2024-06-10 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0013_commentmodel_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='quantity',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
